# Generated by Django 3.1.2 on 2020-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Physics', 'Physics')], max_length=30)),
                ('course_number', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=70)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
    ]
