# Generated by Django 3.1.2 on 2020-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20201027_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Physics', 'Physics'), ('English', 'English'), ('Math', 'Math')], max_length=30),
        ),
    ]
